name: MultiCoins-VaultHook
version: '${project.version}'
main: me.hsgamer.multicoinsvaulthook.MultiCoinsVaultHook
api-version: 1.13
depend: [ Vault, MultiCoins ]
authors: [ HSGamer ]
folia-supported: true
